import type { DomainDefinition, ThreeLessons } from "../../curriculum/contracts";
import { commonClaims, lesson, numberFactor } from "../support/construction";

export const probabilityFormDefinition: DomainDefinition<ThreeLessons> = {
    id: "probability-form",
    number: 7,
    title: "Probability & Form",
    shortTitle: "Probability",
    mark: "◇",
    description: "Use seeded chance, Markov memory, entropy, and surprisal without equating them with creativity.",
    lessons: [
      lesson("probability-form", 1, {
        id: "seeded-chance",
        level: "foundation",
        title: "Seeded Chance",
        shortTitle: "Seeded chance",
        question: "How can a stochastic rule produce an exactly reproducible classroom experiment?",
        objective: "Generate a seeded binary sequence and compare expected and observed proportions.",
        equation: "X_t ~ Bernoulli(p)",
        equationCaption: "A fixed pseudo-random seed reproduces one finite realization.",
        predictionPrompt: "Predict how closely the finite proportion will match p at the selected length.",
        experimentPrompt: "Change seed or length separately and compare finite-sample variation.",
        interpretationPrompt: "Distinguish a probability model, one realization, and a musical design decision.",
        transferPrompt: "Use one seeded rule to generate material you can revise rather than accept automatically.",
        factors: [
          numberFactor("probability", "Probability of A", 0.5, 0.05, 0.95, 0.05, "", "Bernoulli probability for event A."),
          numberFactor("length", "Sequence length", 16, 4, 128, 1, "events", "Number of generated events."),
          numberFactor("seed", "Seed", 2026, 0, 9999, 1, "", "Integer seed for reproducibility."),
        ],
        claimIds: commonClaims,
        sourceIds: [],
        seed: "factor:seed",
      }),
      lesson("probability-form", 2, {
        id: "markov-memory",
        level: "model",
        title: "Markov Memory",
        shortTitle: "Markov memory",
        question: "How does a transition rule create local dependence without planning a global form?",
        objective: "Generate a two-state Markov sequence and compare run length with the stationary distribution.",
        equation: "P(X_(t+1)=j | X_t=i) = P_ij",
        equationCaption: "The next-state distribution depends only on the current modeled state.",
        predictionPrompt: "Predict how a higher stay probability changes repeated runs.",
        experimentPrompt: "Change stay probability only; retain the seed for a controlled comparison.",
        interpretationPrompt: "Explain local memory without calling the chain a style model or composer.",
        transferPrompt: "Map states to musical actions and identify a formal behavior the first-order chain cannot create.",
        factors: [
          numberFactor("stayProbability", "Stay probability", 0.75, 0.05, 0.95, 0.05, "", "Probability of repeating the current state."),
          numberFactor("length", "Sequence length", 32, 4, 128, 1, "events", "Number of generated states."),
          numberFactor("seed", "Seed", 173, 0, 9999, 1, "", "Integer seed for reproducibility."),
        ],
        claimIds: commonClaims,
        sourceIds: [],
        seed: "factor:seed",
      }),
      lesson("probability-form", 3, {
        id: "entropy-surprisal-form",
        level: "critique",
        title: "Entropy, Surprisal, and Form",
        shortTitle: "Entropy & form",
        question: "What does information quantify, and what does it leave out about musical form?",
        objective: "Calculate entropy and event surprisal, then compare them with a finite seeded sequence.",
        equation: "H(X) = -sum p(x) log2 p(x)",
        equationCaption: "Entropy is expected information under a declared distribution, not creativity or quality.",
        predictionPrompt: "Predict where binary entropy is largest and how rare-event surprisal behaves.",
        experimentPrompt: "Change probability only, then inspect entropy, surprisal, and the generated sequence.",
        interpretationPrompt: "Name formal or contextual properties that the entropy value cannot encode.",
        transferPrompt: "Compare two musical sections with an explicit event alphabet and critique that representation.",
        factors: [
          numberFactor("probability", "Probability of A", 0.65, 0.05, 0.95, 0.05, "", "Declared probability for event A."),
          numberFactor("length", "Sample length", 24, 4, 128, 1, "events", "Finite generated sequence length."),
          numberFactor("seed", "Seed", 41, 0, 9999, 1, "", "Integer seed for the finite realization."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: [],
        seed: "factor:seed",
      }),
    ],
};
