import type { DomainDefinition, ThreeLessons } from "../../curriculum/contracts";
import { lesson, numberFactor } from "../support/construction";

export const measurementInferenceDefinition: DomainDefinition<ThreeLessons> = {
    id: "measurement-inference",
    number: 8,
    title: "Measurement & Inference",
    shortTitle: "Measurement",
    mark: "⌁",
    description: "Track provenance, uncertainty, parameter recovery, and descriptive comparison.",
    lessons: [
      lesson("measurement-inference", 1, {
        id: "provenance-and-uncertainty",
        level: "foundation",
        title: "Provenance and Uncertainty",
        shortTitle: "Provenance",
        question: "What must accompany a number before it can function as evidence?",
        objective: "Connect sample count, deterministic noise, method, units, and an uncertainty interval.",
        equation: "CI_95 = mean +/- 1.96 s/sqrt(n)",
        equationCaption: "The displayed interval is a teaching approximation for a synthetic sample, not a universal guarantee.",
        predictionPrompt: "Predict how increasing sample count changes the interval width at fixed noise.",
        experimentPrompt: "Change sample count only and compare uncertainty with the same synthetic seed.",
        interpretationPrompt: "State the population, method, assumptions, and calibration status needed for the claim.",
        transferPrompt: "Rewrite one unsupported musical number as a bounded, provenance-rich observation.",
        factors: [
          numberFactor("sampleCount", "Sample count", 24, 4, 256, 1, "", "Number of deterministic synthetic observations."),
          numberFactor("trueValue", "Generating value", 100, 0, 200, 1, "units", "Known center of the synthetic fixture."),
          numberFactor("noise", "Noise scale", 8, 0, 40, 0.5, "units", "Deterministic pseudo-random variation scale."),
          numberFactor("seed", "Seed", 9, 0, 9999, 1, "", "Seed recorded with the synthetic sample."),
        ],
        claimIds: ["model.deterministic", "measurement.local", "heuristic.transparent", "recommendation.inquiry"],
        sourceIds: ["w3c-webaudio", "w3c-mediacapture"],
        seed: "factor:seed",
      }),
      lesson("measurement-inference", 2, {
        id: "recovering-parameters",
        level: "model",
        title: "Recovering Parameters",
        shortTitle: "Parameter recovery",
        question: "Can the analysis recover a known generating tempo from noisy synthetic onsets?",
        objective: "Estimate tempo from bounded inter-onset intervals and inspect bias and spread.",
        equation: "b_hat = 60 / median(Delta t)",
        equationCaption: "Median-interval recovery is transparent but fails under subdivisions, missing events, and tempo change.",
        predictionPrompt: "Predict how onset jitter changes recovered tempo and interval spread.",
        experimentPrompt: "Change jitter or sample count separately while the generating tempo stays known.",
        interpretationPrompt: "Use recovery error to critique the method, not to grade a performance.",
        transferPrompt: "Design one synthetic failure case before applying an estimator to recorded sound.",
        factors: [
          numberFactor("tempoBpm", "Generating tempo", 120, 40, 220, 1, "BPM", "Known tempo used to generate synthetic onsets."),
          numberFactor("jitterMs", "Onset variation", 18, 0, 120, 1, "ms", "Deterministic onset displacement scale."),
          numberFactor("sampleCount", "Onsets", 24, 6, 128, 1, "", "Number of synthetic onsets."),
          numberFactor("seed", "Seed", 77, 0, 9999, 1, "", "Seed recorded with the fixture."),
        ],
        claimIds: ["model.deterministic", "hypothesis.transcription", "heuristic.transparent"],
        sourceIds: ["snyder-2024"],
        seed: "factor:seed",
      }),
      lesson("measurement-inference", 3, {
        id: "compare-without-grading",
        level: "critique",
        title: "Compare Without Grading",
        shortTitle: "Descriptive comparison",
        question: "How can two event sets be compared without turning difference into a score?",
        objective: "Summarize signed alignment with median and IQR while retaining direction and provenance.",
        equation: "d_i = observed_i - reference_i",
        equationCaption: "Median and IQR describe the selected event alignment; no target grade is defined.",
        predictionPrompt: "Predict how a systematic offset differs from increased spread in the summary.",
        experimentPrompt: "Change center or spread separately and compare descriptive alignment statistics.",
        interpretationPrompt: "Describe timing relation without using better, worse, accurate, or inaccurate.",
        transferPrompt: "Write a neutral rehearsal observation that keeps direction, variability, and context.",
        factors: [
          numberFactor("offsetMs", "Systematic offset", 22, -150, 150, 1, "ms", "Center of the synthetic event differences."),
          numberFactor("spreadMs", "Difference spread", 18, 0, 100, 1, "ms", "Deterministic variability around the center."),
          numberFactor("eventCount", "Event pairs", 16, 4, 64, 1, "", "Number of paired synthetic events."),
          numberFactor("seed", "Seed", 33, 0, 9999, 1, "", "Seed recorded with the comparison."),
        ],
        claimIds: ["model.deterministic", "measurement.local", "recommendation.inquiry"],
        sourceIds: ["demos-palmer-2023", "abalde-2024"],
        seed: "factor:seed",
      }),
    ],
};
