import type { DomainDefinition, ThreeLessons } from "../../curriculum/contracts";
import { chordOptions, commonClaims, lesson, numberFactor, selectFactor, toggleFactor } from "../support/construction";

export const harmonyGeometryDefinition: DomainDefinition<ThreeLessons> = {
    id: "harmony-geometry",
    number: 5,
    title: "Harmony & Geometry",
    shortTitle: "Harmony",
    mark: "△",
    description: "Study pitch-class symmetries, interval structure, graphs, and voice-leading distance.",
    lessons: [
      lesson("harmony-geometry", 1, {
        id: "pitch-class-symmetry",
        level: "foundation",
        title: "Pitch-Class Symmetry",
        shortTitle: "Pitch-class symmetry",
        question: "Which interval properties survive transposition and inversion?",
        objective: "Apply T/I operations and compare interval-class vectors.",
        equation: "T_n(x)=x+n mod 12; I_n(x)=n-x mod 12",
        equationCaption: "The same index n is used directly in T_n and I_n on the twelve pitch classes.",
        predictionPrompt: "Predict whether the interval-class vector changes under the selected operation.",
        experimentPrompt: "Change transposition or inversion while holding the source set fixed.",
        interpretationPrompt: "State the mathematical invariant without claiming identical harmonic function.",
        transferPrompt: "Find one score transformation and name what the pitch-class model omits.",
        factors: [
          selectFactor("set", "Pitch-class set", "major", [
            { value: "major", label: "Major triad {0,4,7}" },
            { value: "minor", label: "Minor triad {0,3,7}" },
            { value: "quartal", label: "Quartal set {0,5,10}" },
            { value: "whole-tone", label: "Whole-tone {0,2,4,6}" },
          ], "Source pitch-class collection."),
          numberFactor("axis", "T/I index n", 0, 0, 11, 1, "pitch classes", "The n in T_n(x)=x+n and I_n(x)=n-x, both modulo 12."),
          toggleFactor("invert", "Use inversion", false, "Switch between transposition and inversion."),
        ],
        claimIds: commonClaims,
        sourceIds: ["frederick-2023"],
      }),
      lesson("harmony-geometry", 2, {
        id: "tonnetz-and-voice-leading",
        level: "model",
        title: "Tonnetz and Voice-Leading",
        shortTitle: "Voice-leading paths",
        question: "How can a graph and an assignment metric describe different kinds of harmonic proximity?",
        objective: "Calculate minimal circular semitone movement and compare it with a shortest path in a selected chord graph.",
        equation: "d_VL(A,B)=min_sigma sum_i |a_i-b_sigma(i)|_12; d_G(A,B)=min_P sum_(e in P) w(e)",
        equationCaption: "The assignment distance and graph-path cost are distinct, explicit proximity models.",
        predictionPrompt: "Predict which target chord is closer under the displayed metric.",
        experimentPrompt: "Change either the target chord or graph family, but not both, and compare the two proximity observables.",
        interpretationPrompt: "Explain why computed proximity does not prove tonal function or perceptual closeness.",
        transferPrompt: "Voice two chords on an instrument and compare embodied constraints with the abstract metric.",
        factors: [
          selectFactor("chordA", "Source chord", "C", chordOptions(), "Source triad."),
          selectFactor("chordB", "Target chord", "Am", chordOptions(), "Target triad."),
          selectFactor("metric", "Graph family", "tonnetz", [
            { value: "tonnetz", label: "P/L/R triadic graph" },
            { value: "chromatic", label: "Chromatic root-distance graph" },
          ], "P/L/R edges cost one transformation; chromatic edges are weighted by circular root distance in semitones."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: ["frederick-2023"],
      }),
      lesson("harmony-geometry", 3, {
        id: "chord-hypotheses",
        level: "critique",
        title: "Chord Hypotheses",
        shortTitle: "Chord hypotheses",
        question: "How should a chroma template's top three chord labels be checked?",
        objective: "Interpret ranked major, minor, and no-chord hypotheses rather than a single asserted label.",
        equation: "score(c)=cosine(chroma, template_c)",
        equationCaption: "Template similarity ranks hypotheses; it does not recover voicing, function, or complete score.",
        predictionPrompt: "Predict how spectral ambiguity changes the gap between the first and second hypotheses.",
        experimentPrompt: "Compare a clean synthetic chord with added ambiguity or local browser audio.",
        interpretationPrompt: "Use confidence separation and musical context to accept, revise, or reject the ranking.",
        transferPrompt: "Check the top three hypotheses against a notated or performed cadence.",
        factors: [
          numberFactor("root", "Synthetic root", 0, 0, 11, 1, "pitch class", "Root pitch class for the synthetic chroma fixture."),
          selectFactor("quality", "Synthetic quality", "major", [
            { value: "major", label: "Major" },
            { value: "minor", label: "Minor" },
          ], "Triad quality for the synthetic fixture."),
          numberFactor("ambiguity", "Spectral ambiguity", 0.15, 0, 1, 0.05, "", "Deterministic energy spread across unrelated pitch classes."),
        ],
        claimIds: ["measurement.local", "hypothesis.transcription", "heuristic.transparent", "recommendation.inquiry"],
        sourceIds: ["w3c-webaudio"],
        inputModes: ["synthetic", "microphone", "file"],
      }),
    ],
};
