import type { DomainDefinition, ThreeLessons } from "../../curriculum/contracts";
import { commonClaims, lesson, numberFactor, selectFactor } from "../support/construction";

export const timbreAcousticsDefinition: DomainDefinition<ThreeLessons> = {
    id: "timbre-acoustics",
    number: 6,
    title: "Timbre & Acoustics",
    shortTitle: "Timbre",
    mark: "▥",
    description: "Connect resonance, partials, spectra, windows, sampling, aliasing, and envelopes.",
    lessons: [
      lesson("timbre-acoustics", 1, {
        id: "resonance-modes-partials",
        level: "foundation",
        title: "Resonance, Modes, and Partials",
        shortTitle: "Modes & partials",
        question: "How do boundary assumptions generate a family of resonant frequencies?",
        objective: "Calculate idealized string modes and construct an additive spectrum.",
        equation: "f_n = n v / (2L)",
        equationCaption: "Ideal fixed-string modes omit stiffness, damping, radiation, and instrument geometry.",
        predictionPrompt: "Predict how doubling length changes every idealized mode.",
        experimentPrompt: "Change length or mode count one at a time and inspect the partial series.",
        interpretationPrompt: "Separate an ideal mode calculation from a measured instrument spectrum.",
        transferPrompt: "Identify one real-instrument effect absent from the ideal string model.",
        factors: [
          numberFactor("length", "String length", 0.65, 0.2, 2, 0.01, "m", "Ideal vibrating length."),
          numberFactor("waveSpeed", "Wave speed", 143, 40, 500, 1, "m/s", "Ideal transverse wave speed."),
          numberFactor("partialCount", "Modes shown", 8, 1, 24, 1, "", "Number of ideal modes in the display."),
        ],
        claimIds: commonClaims,
        sourceIds: ["marjieh-2024"],
      }),
      lesson("timbre-acoustics", 2, {
        id: "fourier-windows-aliasing",
        level: "model",
        title: "Fourier, Windows, and Aliasing",
        shortTitle: "Fourier & aliasing",
        question: "What do frame size, windowing, and sample rate permit a spectrum to show?",
        objective: "Relate bin spacing to frame duration and fold frequencies above Nyquist.",
        equation: "Delta f = fs/N; f_alias = |((f+fs/2) mod fs)-fs/2|",
        equationCaption: "Finite sampled frames constrain frequency representation.",
        predictionPrompt: "Predict how doubling frame size changes frequency-bin spacing.",
        experimentPrompt: "Change frame size or sample rate separately and compare resolution and alias frequency.",
        interpretationPrompt: "Explain why a plotted peak is not infinitely precise or free of leakage.",
        transferPrompt: "Choose analysis settings for a low note and justify the time–frequency trade-off.",
        factors: [
          numberFactor("frequencyHz", "Signal frequency", 1000, 20, 30000, 10, "Hz", "Synthetic sinusoid before sampling."),
          selectFactor("sampleRateHz", "Sample rate", "48000", [
            { value: "22050", label: "22,050 Hz" },
            { value: "44100", label: "44,100 Hz" },
            { value: "48000", label: "48,000 Hz" },
          ], "Sampling frequency."),
          selectFactor("frameSize", "Hann frame", "2048", [
            { value: "2048", label: "2,048 samples" },
            { value: "4096", label: "4,096 samples" },
          ], "Analysis frame with 50% overlap in recorded-audio mode."),
        ],
        claimIds: commonClaims,
        sourceIds: ["w3c-webaudio"],
      }),
      lesson("timbre-acoustics", 3, {
        id: "time-varying-timbre",
        level: "critique",
        title: "Time-Varying Timbre",
        shortTitle: "Timbre through time",
        question: "Why can one spectrum not describe an evolving musical sound?",
        objective: "Relate envelope and modulation parameters to a time-indexed spectral-centroid proxy.",
        equation: "x(t)=A(t) sum a_k(t) sin(2 pi k f0 t)",
        equationCaption: "Both amplitude and partial weights may vary through time.",
        predictionPrompt: "Predict when the brightest point occurs under the selected envelope and modulation.",
        experimentPrompt: "Change attack or modulation depth while holding the other factors fixed.",
        interpretationPrompt: "Compare a trajectory with listening while retaining the uncalibrated boundary.",
        transferPrompt: "Describe the attack and decay of one instrumental tone with both words and a measured feature.",
        factors: [
          numberFactor("attackMs", "Attack", 80, 5, 1000, 5, "ms", "Duration of the synthetic rise."),
          numberFactor("decayMs", "Decay", 900, 100, 4000, 25, "ms", "Duration of the synthetic decay."),
          numberFactor("modulationHz", "Brightness modulation", 2, 0, 12, 0.25, "Hz", "Rate of deterministic partial-weight modulation."),
          numberFactor("modulationDepth", "Modulation depth", 0.45, 0, 1, 0.05, "", "Depth of spectral-centroid movement."),
        ],
        claimIds: ["model.deterministic", "measurement.local", "literature.context", "heuristic.transparent"],
        sourceIds: ["marjieh-2024", "w3c-webaudio"],
        inputModes: ["synthetic", "microphone", "file"],
      }),
    ],
};
