import type { DomainDefinition, ThreeLessons } from "../../curriculum/contracts";
import { commonClaims, contextualClaims, lesson, numberFactor } from "../support/construction";

const lessons = [
      lesson("pitch-tuning", 1, {
        id: "ratios-logs-cents",
        level: "foundation",
        title: "Ratios, Logs, and Cents",
        shortTitle: "Ratios & cents",
        question: "Why does an additive interval scale require a logarithm of a frequency ratio?",
        objective: "Convert ratios to cents and back, retaining a reference frequency.",
        equation: "c = 1200 log2(f2/f1)",
        equationCaption: "Cents add when frequency ratios multiply.",
        predictionPrompt: "Predict the cents value of the selected integer ratio.",
        experimentPrompt: "Change one ratio term and compare target frequency and interval size.",
        interpretationPrompt: "Separate exact frequency arithmetic from tuning preference or practice.",
        transferPrompt: "Calculate one interval from your instrument or score using an explicit reference.",
        factors: [
          numberFactor("numerator", "Ratio numerator", 3, 1, 16, 1, "", "Upper integer in the frequency ratio."),
          numberFactor("denominator", "Ratio denominator", 2, 1, 16, 1, "", "Lower integer in the frequency ratio."),
          numberFactor("referenceHz", "Reference frequency", 220, 40, 880, 1, "Hz", "Frequency multiplied by the ratio."),
        ],
        claimIds: commonClaims,
        sourceIds: ["marjieh-2024"],
      }),
      lesson("pitch-tuning", 2, {
        id: "temperaments-and-commas",
        level: "model",
        title: "Temperaments and Commas",
        shortTitle: "Temperaments",
        question: "How closely can equal divisions approximate a selected frequency ratio?",
        objective: "Find the nearest EDO step and quantify signed cents error and idealized beating.",
        equation: "f_n/f_0 = 2^(n/m)",
        equationCaption: "m equal logarithmic divisions partition an octave ratio of 2:1.",
        predictionPrompt: "Predict whether increasing divisions reduces the selected ratio's error.",
        experimentPrompt: "Change divisions only; compare nearest step, cents error, and beating rate.",
        interpretationPrompt: "Explain why smaller cents error does not establish the best musical temperament.",
        transferPrompt: "Choose one repertoire context and identify a tuning trade-off worth hearing.",
        factors: [
          numberFactor("divisions", "Equal divisions", 12, 5, 53, 1, "EDO", "Equal logarithmic divisions per octave."),
          numberFactor("numerator", "Target numerator", 3, 1, 16, 1, "", "Numerator of the target ratio."),
          numberFactor("denominator", "Target denominator", 2, 1, 16, 1, "", "Denominator of the target ratio."),
          numberFactor("referenceHz", "Reference frequency", 220, 40, 880, 1, "Hz", "Reference used for the idealized beating calculation."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: ["marjieh-2024"],
      }),
      lesson("pitch-tuning", 3, {
        id: "timbre-changes-consonance",
        level: "critique",
        title: "Timbre Changes Consonance",
        shortTitle: "Timbre & consonance",
        question: "Why can the same fundamental interval change when its spectrum changes?",
        objective: "Compare partial coincidences and a transparent roughness proxy across timbres.",
        equation: "S(f) = sum a_k delta(f-k f0)",
        equationCaption: "The partial amplitudes define the synthetic spectrum used by the proxy.",
        predictionPrompt: "Predict how adding bright upper partials changes the displayed coincidence and roughness proxies.",
        experimentPrompt: "Hold the interval fixed while changing partial count or spectral roll-off.",
        interpretationPrompt: "Connect the model to empirical consonance research without universalizing preference.",
        transferPrompt: "Compare the same dyad with two instrumental registrations and describe, do not score, the change.",
        factors: [
          numberFactor("intervalCents", "Interval", 700, 0, 1200, 5, "cents", "Fundamental interval between the two synthetic tones."),
          numberFactor("partialCount", "Partials", 8, 1, 24, 1, "", "Number of harmonic partials in each tone."),
          numberFactor("rolloff", "Spectral roll-off", 1, 0.2, 3, 0.1, "power", "Amplitude exponent: a_k = 1/k^p."),
        ],
        claimIds: ["math.identity", ...contextualClaims],
        sourceIds: ["marjieh-2024"],
      }),
] as const satisfies ThreeLessons;

export const pitchTuningDefinition: DomainDefinition<typeof lessons> = {
  id: "pitch-tuning",
  number: 4,
  title: "Pitch & Tuning",
  shortTitle: "Pitch",
  mark: "⋔",
  description: "Connect ratios, logarithms, cents, temperaments, beating, and timbre.",
  lessons,
};
