export const portfolioStorageKey = "musicaMathematica.learning.v2";
export const legacyPortfolioStorageKey = "ensembleCouplingLab.learning.v1";
export const maximumTrialsPerLesson = 12;
export const maximumTracePointsPerTrial = 256;
export const maximumObservablesPerTrial = 24;
export const maximumExtensionFactorsPerTrial = 16;
export const maximumResponseCodePoints = 16_384;
export const maximumLongValueCodePoints = 1_024;
export const maximumExtensionFactorCodePoints = 512;
export const maximumLabelCodePoints = 256;
export const maximumPortfolioJsonBytes = 4 * 1024 * 1024;
export const maximumRawPortfolioJsonBytes = 8 * 1024 * 1024;
export const traceCompactionTiers = [128, 64, 32, 16, 0] as const;
export const legacyLessonMapping = Object.freeze({ "lock-in": "lock-in-and-order", latency: "delay-jitter-topology", "low-latency-route": "delay-jitter-topology", "diagnose-instability": "delay-jitter-topology", click: "external-pulse-or-peer-adaptation", "click-or-peer-coupling": "external-pulse-or-peer-adaptation", "compose-with-latency": "external-pulse-or-peer-adaptation" } as const);
export type MigratedEnsembleLessonId = (typeof legacyLessonMapping)[keyof typeof legacyLessonMapping];
export const attemptKey = (labId: string, lessonId: string): string => `${labId}:${lessonId}`;
