import type { CurriculumDomainId, CurriculumLessonReader, FactorDefinition, FactorValue, ObservableRecord, TracePoint } from "../../curriculum/contracts";
import { isLessonStage, lessonStages } from "../stages";
import { attemptKey, maximumTracePointsPerTrial, maximumTrialsPerLesson } from "./constants";
import type { LearningPortfolioV2, LessonAttemptV2, TrialSnapshotV2 } from "./schema-v2";

export function isLearningPortfolioV2(value: unknown, curriculum: CurriculumLessonReader): value is LearningPortfolioV2 {
  return isRecord(value) && value.version === 2 && isActive(value.active) && isRecord(value.attempts)
    && isKnownLesson(value.active.labId, value.active.lessonId, curriculum)
    && Object.entries(value.attempts).every(([key, attempt]) => isLessonAttemptV2(attempt, curriculum) && key === attemptKey(attempt.labId, attempt.lessonId));
}
export const isLessonAttemptV2 = (value: unknown, curriculum: CurriculumLessonReader): value is LessonAttemptV2 => isAttemptShape(value, curriculum) && hasStageContent(value);
export function isTrialSnapshotV2(value: unknown, curriculum: CurriculumLessonReader): value is TrialSnapshotV2 {
  if (!isRecord(value) || typeof value.id !== "string" || !value.id.trim() || typeof value.labId !== "string" || typeof value.lessonId !== "string" || !isKnownLesson(value.labId, value.lessonId, curriculum)) return false;
  if (typeof value.protocolId !== "string" || !value.protocolId.trim() || typeof value.deterministic !== "boolean" || typeof value.recordedAt !== "string" || !iso(value.recordedAt) || !isRecord(value.factors)) return false;
  const lesson = curriculum.lessonById(value.labId, value.lessonId); const factors = value.factors as Record<string, unknown>;
  if (!lesson || !lesson.factors.every((definition) => validFactor(factors[definition.id], definition)) || !Object.entries(factors).every(([id, factor]) => isFactorValue(factor) && (lesson.factors.find((definition) => definition.id === id) === undefined || validFactor(factor, lesson.factors.find((definition) => definition.id === id)!)))) return false;
  return Array.isArray(value.observables) && value.observables.every(isObservable) && Array.isArray(value.trace) && value.trace.length <= maximumTracePointsPerTrial && value.trace.every(isTrace) && isProvenance(value.provenance) && (value.seed === undefined || typeof value.seed === "string") && (value.note === undefined || typeof value.note === "string");
}
export function sanitizePortfolio(portfolio: LearningPortfolioV2, curriculum: CurriculumLessonReader): LearningPortfolioV2 {
  const attempts = Object.fromEntries(Object.entries(portfolio.attempts).flatMap(([key, attempt]) => !isSanitizableAttempt(attempt, curriculum) ? [] : [[key, { version: 2 as const, labId: attempt.labId, lessonId: attempt.lessonId, stage: attempt.stage, ...(text(attempt.prediction) ? { prediction: attempt.prediction.trim() } : {}), ...(text(attempt.explanation) ? { explanation: attempt.explanation.trim() } : {}), ...(text(attempt.performanceReflection) ? { performanceReflection: attempt.performanceReflection.trim() } : {}), ...(text(attempt.transferResponse) ? { transferResponse: attempt.transferResponse.trim() } : {}), trials: attempt.trials.slice(-maximumTrialsPerLesson).map(sanitizeTrial), updatedAt: attempt.updatedAt }]]));
  return { version: 2, active: { ...portfolio.active }, attempts };
}
export function sanitizeTrial(trial: TrialSnapshotV2): TrialSnapshotV2 {
  return { id: trial.id.trim(), labId: trial.labId, lessonId: trial.lessonId, protocolId: trial.protocolId.trim(), deterministic: trial.deterministic, ...(trial.seed ? { seed: trial.seed } : {}), recordedAt: trial.recordedAt, factors: Object.fromEntries(Object.entries(trial.factors).filter(([, value]) => isFactorValue(value))), observables: trial.observables.map((item) => ({ ...item })), trace: capTrace(trial.trace), provenance: { source: trial.provenance.source, calibration: "uncalibrated", method: trial.provenance.method, ...(trial.provenance.sampleRateHz === undefined ? {} : { sampleRateHz: trial.provenance.sampleRateHz }), ...(trial.provenance.frameSize === undefined ? {} : { frameSize: trial.provenance.frameSize }), ...(trial.provenance.hopSize === undefined ? {} : { hopSize: trial.provenance.hopSize }), ...(trial.provenance.droppedFrames === undefined ? {} : { droppedFrames: trial.provenance.droppedFrames }) }, ...(trial.note?.trim() ? { note: trial.note.trim() } : {}) };
}
const isAttemptShape = (value: unknown, curriculum: CurriculumLessonReader): value is LessonAttemptV2 => isRecord(value) && value.version === 2 && isKnownLesson(value.labId, value.lessonId, curriculum) && isLessonStage(value.stage) && Array.isArray(value.trials) && value.trials.length <= maximumTrialsPerLesson && value.trials.every((trial) => isTrialSnapshotV2(trial, curriculum) && trial.labId === value.labId && trial.lessonId === value.lessonId) && typeof value.updatedAt === "string" && iso(value.updatedAt) && [value.prediction, value.explanation, value.performanceReflection, value.transferResponse].every((item) => item === undefined || text(item));
const isSanitizableAttempt = (value: unknown, curriculum: CurriculumLessonReader): value is LessonAttemptV2 => isRecord(value) && value.version === 2 && isKnownLesson(value.labId, value.lessonId, curriculum) && isLessonStage(value.stage) && Array.isArray(value.trials) && typeof value.updatedAt === "string" && [value.prediction, value.explanation, value.performanceReflection, value.transferResponse].every((item) => item === undefined || typeof item === "string");
const hasStageContent = (attempt: LessonAttemptV2): boolean => { const i = lessonStages.indexOf(attempt.stage); return (i < lessonStages.indexOf("experiment") || text(attempt.prediction)) && (i < lessonStages.indexOf("compare") || attempt.trials.length >= 2) && (i < lessonStages.indexOf("perform") || text(attempt.explanation)) && (i < lessonStages.indexOf("transfer") || text(attempt.performanceReflection)) && (i < lessonStages.indexOf("debrief") || text(attempt.transferResponse)); };
const isActive = (value: unknown): value is LearningPortfolioV2["active"] => isRecord(value) && typeof value.labId === "string" && typeof value.lessonId === "string";
const isKnownLesson = (domainId: unknown, lessonId: unknown, curriculum: CurriculumLessonReader): domainId is CurriculumDomainId => typeof domainId === "string" && typeof lessonId === "string" && curriculum.lessonById(domainId, lessonId) !== undefined;
const validFactor = (value: unknown, definition: FactorDefinition): boolean => definition.kind === "number" ? typeof value === "number" && Number.isFinite(value) && value >= definition.min && value <= definition.max : definition.kind === "select" ? typeof value === "string" && definition.options.some((option) => option.value === value) : typeof value === "boolean";
const isFactorValue = (value: unknown): value is FactorValue => typeof value === "string" || typeof value === "boolean" || typeof value === "number" && Number.isFinite(value);
const isObservable = (value: unknown): value is ObservableRecord => isRecord(value) && typeof value.id === "string" && typeof value.label === "string" && (typeof value.value === "string" || typeof value.value === "number" && Number.isFinite(value.value)) && (value.unit === null || typeof value.unit === "string") && typeof value.claimId === "string" && ["instantaneous", "terminal-mean", "range", "distribution"].includes(String(value.aggregation)) && (value.precision === undefined || typeof value.precision === "number" && Number.isInteger(value.precision) && value.precision >= 0 && value.precision <= 100);
const isTrace = (value: unknown): value is TracePoint => isRecord(value) && typeof value.x === "number" && Number.isFinite(value.x) && typeof value.y === "number" && Number.isFinite(value.y) && typeof value.series === "string";
const isProvenance = (value: unknown): boolean => isRecord(value) && ["model", "synthetic", "microphone", "file"].includes(String(value.source)) && value.calibration === "uncalibrated" && typeof value.method === "string" && [value.sampleRateHz, value.frameSize, value.hopSize, value.droppedFrames].every((item) => item === undefined || typeof item === "number" && Number.isFinite(item));
const capTrace = (trace: readonly TracePoint[]): TracePoint[] => trace.length <= maximumTracePointsPerTrial ? trace.map((point) => ({ ...point })) : Array.from({ length: maximumTracePointsPerTrial }, (_, index) => ({ ...trace[Math.round(index * (trace.length - 1) / (maximumTracePointsPerTrial - 1))]! }));
const text = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0;
const iso = (value: string): boolean => Number.isFinite(Date.parse(value));
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
