import { advancedLabDomains } from "./catalogAdvancedDomains";
import {
  commonClaims,
  contextualClaims,
  lesson,
  numberFactor,
  selectFactor,
} from "./catalogSupport";
import type { LabDomain, LabLesson } from "./types";

export const labCatalog: readonly LabDomain[] = [
  {
    id: "phase-proportion",
    number: 1,
    title: "Phase & Proportion",
    shortTitle: "Phase",
    mark: "◯",
    description: "Move between tempo, period, ratio, return time, and circular phase.",
    lessons: [
      lesson("phase-proportion", 1, {
        id: "from-bpm-to-period",
        level: "foundation",
        title: "From BPM to Period",
        shortTitle: "BPM ↔ period",
        question: "How does a tempo become a duration, and which units must travel with the calculation?",
        objective: "Convert tempo to beat and bar duration, then test the inverse conversion.",
        equation: "T = 60 / b",
        equationCaption: "With b in beats per minute, T is seconds per beat.",
        predictionPrompt: "Before changing tempo, predict how doubling BPM changes beat duration.",
        experimentPrompt: "Change BPM only; compare beat and bar duration in two runs.",
        interpretationPrompt: "State the inverse relationship without treating a tempo label as performed timing.",
        transferPrompt: "Choose a score passage and calculate the time represented by one bar.",
        factors: [
          numberFactor("bpm", "Tempo", 90, 30, 240, 1, "BPM", "Beats per minute."),
          numberFactor("beatsPerBar", "Beats per bar", 4, 1, 12, 1, "beats", "Equal beats used in the bar-duration calculation."),
        ],
        claimIds: commonClaims,
        sourceIds: ["snyder-2024"],
      }),
      lesson("phase-proportion", 2, {
        id: "polyrhythm-return-times",
        level: "model",
        title: "Polyrhythm Return Times",
        shortTitle: "Return times",
        question: "When must two integer pulse cycles realign?",
        objective: "Use greatest common divisors and least common multiples to explain exact returns.",
        equation: "L = lcm(p, q) = |pq| / gcd(p, q)",
        equationCaption: "L is the number of equal lattice subdivisions inside one shared cycle; both layers realign at that cycle's endpoint.",
        predictionPrompt: "Predict whether 4:2 returns sooner or later than 3:2.",
        experimentPrompt: "Change one pulse count, record a second run, and inspect the onset lattice.",
        interpretationPrompt: "Separate exact mathematical alignment from perceived beat, accent, or groove.",
        transferPrompt: "Find one notated polyrhythm and identify its mathematical return point.",
        factors: [
          numberFactor("pulseA", "Layer A pulses", 3, 1, 12, 1, "pulses / shared cycle", "Integer onset count distributed through one shared cycle."),
          numberFactor("pulseB", "Layer B pulses", 2, 1, 12, 1, "pulses / shared cycle", "Integer onset count distributed through the same shared cycle."),
          numberFactor("bpm", "Shared-cycle reference tempo", 90, 30, 180, 1, "BPM", "For this conversion only, one shared cycle is assigned one reference beat of duration 60 / BPM seconds."),
        ],
        claimIds: commonClaims,
        sourceIds: ["jacoby-2024", "snyder-2024"],
      }),
      lesson("phase-proportion", 3, {
        id: "phase-on-the-circle",
        level: "critique",
        title: "Phase on the Circle",
        shortTitle: "Circular phase",
        question: "Why is phase a circular quantity rather than an ordinary distance?",
        objective: "Calculate wrapped phase and the shortest signed circular difference.",
        equation: "phi(t) = (t / T) mod 1",
        equationCaption: "One full cycle is identified with zero on the unit circle.",
        predictionPrompt: "Predict the shortest direction between the two phases after the selected time.",
        experimentPrompt: "Change one period or offset and compare wrapped phase differences.",
        interpretationPrompt: "Explain what circular distance captures and which musical timing details it omits.",
        transferPrompt: "Describe a musical cue that phase alone cannot represent.",
        factors: [
          numberFactor("periodA", "Period A", 1, 0.2, 4, 0.05, "s", "Cycle duration for oscillator A."),
          numberFactor("periodB", "Period B", 1.5, 0.2, 4, 0.05, "s", "Cycle duration for oscillator B."),
          numberFactor("elapsed", "Elapsed time", 3, 0, 16, 0.1, "s", "Time at which phase is sampled."),
          numberFactor("offset", "B phase offset", 0, -0.5, 0.5, 0.01, "cycles", "Initial phase of B relative to A."),
        ],
        claimIds: commonClaims,
        sourceIds: ["snyder-2024"],
      }),
    ],
  },
  {
    id: "ensemble-dynamics",
    number: 2,
    title: "Ensemble Dynamics",
    shortTitle: "Ensemble",
    mark: "⌁",
    description: "Explore phase lock-in, delay, network topology, and external forcing.",
    lessons: [
      lesson("ensemble-dynamics", 1, {
        id: "lock-in-and-order",
        level: "foundation",
        title: "Lock-In and Order",
        shortTitle: "Lock-in & order",
        question: "When does mutual adjustment produce a coherent phase pattern in this model?",
        objective: "Relate coupling strength to the Kuramoto order parameter without grading musicianship.",
        equation: "r = |N^-1 sum exp(i theta_j)|",
        equationCaption: "The order parameter r is 0–1 phase concentration, not musical quality.",
        predictionPrompt: "Predict how stronger peer coupling changes terminal coherence.",
        experimentPrompt: "Change coupling only and compare deterministic eight-second trials.",
        interpretationPrompt: "Explain model lock-in and name at least one missing human coordination cue.",
        transferPrompt: "Design a listening cue that could be tested separately with players.",
        factors: [
          numberFactor("musicianCount", "Musicians", 8, 2, 24, 1, "", "Number of model oscillators."),
          numberFactor("tempoBpm", "Tempo", 104, 40, 220, 1, "BPM", "Mean natural tempo."),
          numberFactor("tempoSpreadBpm", "Tempo spread", 12, 0, 30, 0.5, "BPM", "Deterministic spread of natural tempi."),
          numberFactor("couplingStrength", "Peer coupling", 0.25, 0, 4, 0.05, "", "Mutual phase-adjustment strength."),
        ],
        claimIds: ["model.ensemble", "heuristic.transparent", "literature.context", "recommendation.inquiry"],
        sourceIds: ["demos-palmer-2023", "abalde-2024"],
      }),
      lesson("ensemble-dynamics", 2, {
        id: "delay-jitter-topology",
        level: "model",
        title: "Delay, Jitter, and Topology",
        shortTitle: "Delay & topology",
        question: "How do fixed delay, varying delay, and who listens to whom alter the model?",
        objective: "Compare delayed network configurations using one controlled factor change.",
        equation: "dtheta_i/dt = omega_i + K d_i^-1/2 sum A_ij sin(theta_j(t-tau)-theta_i)",
        equationCaption: "The implemented peer term includes square-root degree normalization; jitter and texture remain transparent heuristics.",
        predictionPrompt: "Predict which selected factor most changes coherence and phase spread.",
        experimentPrompt: "Change delay, jitter, or topology one at a time; keep the remaining factors fixed.",
        interpretationPrompt: "Distinguish a model stressor from a diagnosis of a real route or rehearsal.",
        transferPrompt: "List the route measurements needed before making a deployment claim.",
        factors: [
          numberFactor("latencyMs", "One-way delay", 55, 0, 250, 1, "ms", "Configured model delay, not measured latency."),
          numberFactor("jitterMs", "Delay variation", 18, 0, 80, 1, "ms", "Qualitative jitter control."),
          numberFactor("couplingStrength", "Peer coupling", 1.1, 0, 4, 0.05, "", "Peer phase-adjustment strength."),
          selectFactor("topology", "Listening topology", "leader-follower", [
            { value: "all-to-all", label: "All-to-all" },
            { value: "leader-follower", label: "Leader–follower" },
            { value: "sections", label: "Sections" },
          ], "Who receives modeled phase information from whom."),
        ],
        claimIds: ["model.ensemble", "heuristic.transparent", "literature.context", "recommendation.inquiry"],
        sourceIds: ["demos-palmer-2023", "abalde-2024"],
      }),
      lesson("ensemble-dynamics", 3, {
        id: "external-pulse-or-peer-adaptation",
        level: "critique",
        title: "External Pulse or Peer Adaptation",
        shortTitle: "Pulse or peers",
        question: "What changes when the model follows an external pulse instead of one another?",
        objective: "Compare timing concentration and peer-coupling share without declaring one strategy better.",
        equation: "dtheta_i/dt = peer_i + C sin(Omega t - theta_i)",
        equationCaption: "External forcing C is modeled separately from peer coupling K.",
        predictionPrompt: "Predict how stronger click forcing changes phase spread and peer share.",
        experimentPrompt: "Record one peer-led and one externally forced strategy.",
        interpretationPrompt: "Choose a musical criterion before interpreting the trade-off.",
        transferPrompt: "Draft a reversible click policy for one passage.",
        factors: [
          numberFactor("clickTrackStrength", "External pulse", 2.2, 0, 4, 0.05, "", "Strength of the common external phase force."),
          numberFactor("couplingStrength", "Peer coupling", 0.35, 0, 4, 0.05, "", "Strength of mutual adjustment."),
          numberFactor("tempoSpreadBpm", "Tempo spread", 10, 0, 30, 0.5, "BPM", "Deterministic natural-tempo variation."),
          numberFactor("tempoBpm", "Tempo", 116, 40, 220, 1, "BPM", "Mean natural tempo and external pulse rate."),
        ],
        claimIds: ["model.ensemble", "heuristic.transparent", "literature.context", "recommendation.inquiry"],
        sourceIds: ["demos-palmer-2023", "abalde-2024"],
      }),
    ],
  },
  {
    id: "rhythm-meter",
    number: 3,
    title: "Rhythm & Meter",
    shortTitle: "Rhythm",
    mark: "▥",
    description: "Construct cyclic onset patterns and test competing metric representations.",
    lessons: [
      lesson("rhythm-meter", 1, {
        id: "cycles-and-euclidean-rhythm",
        level: "foundation",
        title: "Cycles and Euclidean Rhythm",
        shortTitle: "Cycles & Euclid",
        question: "What stays invariant when onsets are distributed and rotated on a cycle?",
        objective: "Build a Euclidean onset pattern and separate interval structure from downbeat choice.",
        equation: "E(k,n)[i] = 1 iff (ik mod n) < k",
        equationCaption: "This deterministic construction distributes k binary onsets over n steps.",
        predictionPrompt: "Predict whether rotation changes density or only onset positions.",
        experimentPrompt: "Change rotation, then change pulse count in a separate comparison.",
        interpretationPrompt: "Distinguish cyclic equivalence from performed accent and cultural meaning.",
        transferPrompt: "Map one generated cycle to an instrumental pattern and choose an accent deliberately.",
        factors: [
          numberFactor("steps", "Cycle length", 16, 4, 32, 1, "steps", "Number of equal positions in the cycle."),
          numberFactor("pulses", "Onsets", 5, 0, 16, 1, "onsets", "Onsets distributed across the cycle."),
          numberFactor("rotation", "Rotation", 0, -16, 16, 1, "steps", "Cyclic displacement of the pattern."),
        ],
        claimIds: commonClaims,
        sourceIds: ["jacoby-2024", "snyder-2024"],
      }),
      lesson("rhythm-meter", 2, {
        id: "autocorrelation-spectrum-meter",
        level: "model",
        title: "Autocorrelation, Spectrum, and Meter",
        shortTitle: "Meter profiles",
        question: "Which periodicities are present in an onset pattern, and why can meter remain ambiguous?",
        objective: "Compare circular autocorrelation, a discrete spectrum, and ranked equal-subdivision candidates.",
        equation: "R[l] = sum x[n]x[(n+l) mod N]",
        equationCaption: "Autocorrelation counts cyclic onset overlap at each lag.",
        predictionPrompt: "Predict the strongest non-zero lag before viewing the profile.",
        experimentPrompt: "Change one onset parameter and compare the ranked metric candidates.",
        interpretationPrompt: "Explain why a high alignment score is not a listener's definitive meter.",
        transferPrompt: "Mark two plausible meters for the same pattern and perform both accent schemes.",
        factors: [
          numberFactor("steps", "Cycle length", 12, 4, 32, 1, "steps", "Number of positions in the cyclic onset vector."),
          numberFactor("pulses", "Onsets", 5, 1, 12, 1, "onsets", "Distributed onsets used to generate the vector."),
          numberFactor("rotation", "Rotation", 0, -12, 12, 1, "steps", "Cyclic downbeat displacement."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: ["jacoby-2024", "snyder-2024"],
      }),
      lesson("rhythm-meter", 3, {
        id: "recorded-onset-hypotheses",
        level: "critique",
        title: "Recorded-Onset Hypotheses",
        shortTitle: "Onset hypotheses",
        question: "How should ranked onset and tempo estimates be interpreted when sound replaces a clean binary pattern?",
        objective: "Inspect multiple hypotheses, method settings, and uncertainty without treating transcription as truth.",
        equation: "flux_t = sum max(0, |X_t|-|X_(t-1)|)",
        equationCaption: "Positive spectral flux is one onset-strength feature, not a complete rhythm transcription.",
        predictionPrompt: "Predict how a stricter onset threshold changes the number of detected events.",
        experimentPrompt: "Compare synthetic, microphone, or file input locally; retain only derived features.",
        interpretationPrompt: "Name evidence that would confirm or reject the top tempo and meter hypotheses.",
        transferPrompt: "Check one ranked hypothesis against a score, tapping task, or close listening.",
        factors: [
          numberFactor("tempoBpm", "Synthetic tempo", 108, 40, 220, 1, "BPM", "Tempo of the privacy-safe synthetic fixture."),
          numberFactor("threshold", "Onset threshold", 0.35, 0.05, 0.95, 0.05, "", "Relative spectral-flux cutoff."),
          selectFactor("meterBias", "Candidate family", "mixed", [
            { value: "mixed", label: "Mixed" },
            { value: "duple", label: "Duple" },
            { value: "triple", label: "Triple" },
          ], "Candidate set used by the lightweight ranking stage."),
        ],
        claimIds: ["measurement.local", "hypothesis.transcription", "literature.context", "recommendation.inquiry"],
        sourceIds: ["jacoby-2024", "snyder-2024", "w3c-webaudio", "w3c-mediacapture"],
        inputModes: ["synthetic", "microphone", "file"],
      }),
    ],
  },
  {
    id: "pitch-tuning",
    number: 4,
    title: "Pitch & Tuning",
    shortTitle: "Pitch",
    mark: "⋔",
    description: "Connect ratios, logarithms, cents, temperaments, beating, and timbre.",
    lessons: [
      lesson("pitch-tuning", 1, {
        id: "ratios-logs-cents",
        level: "foundation",
        title: "Ratios, Logs, and Cents",
        shortTitle: "Ratios & cents",
        question: "Why does an additive interval scale require a logarithm of a frequency ratio?",
        objective: "Convert ratios to cents and back, retaining a reference frequency.",
        equation: "c = 1200 log2(f2/f1)",
        equationCaption: "Cents add when frequency ratios multiply.",
        predictionPrompt: "Predict the cents value of the selected integer ratio.",
        experimentPrompt: "Change one ratio term and compare target frequency and interval size.",
        interpretationPrompt: "Separate exact frequency arithmetic from tuning preference or practice.",
        transferPrompt: "Calculate one interval from your instrument or score using an explicit reference.",
        factors: [
          numberFactor("numerator", "Ratio numerator", 3, 1, 16, 1, "", "Upper integer in the frequency ratio."),
          numberFactor("denominator", "Ratio denominator", 2, 1, 16, 1, "", "Lower integer in the frequency ratio."),
          numberFactor("referenceHz", "Reference frequency", 220, 40, 880, 1, "Hz", "Frequency multiplied by the ratio."),
        ],
        claimIds: commonClaims,
        sourceIds: ["marjieh-2024"],
      }),
      lesson("pitch-tuning", 2, {
        id: "temperaments-and-commas",
        level: "model",
        title: "Temperaments and Commas",
        shortTitle: "Temperaments",
        question: "How closely can equal divisions approximate a selected frequency ratio?",
        objective: "Find the nearest EDO step and quantify signed cents error and idealized beating.",
        equation: "f_n/f_0 = 2^(n/m)",
        equationCaption: "m equal logarithmic divisions partition an octave ratio of 2:1.",
        predictionPrompt: "Predict whether increasing divisions reduces the selected ratio's error.",
        experimentPrompt: "Change divisions only; compare nearest step, cents error, and beating rate.",
        interpretationPrompt: "Explain why smaller cents error does not establish the best musical temperament.",
        transferPrompt: "Choose one repertoire context and identify a tuning trade-off worth hearing.",
        factors: [
          numberFactor("divisions", "Equal divisions", 12, 5, 53, 1, "EDO", "Equal logarithmic divisions per octave."),
          numberFactor("numerator", "Target numerator", 3, 1, 16, 1, "", "Numerator of the target ratio."),
          numberFactor("denominator", "Target denominator", 2, 1, 16, 1, "", "Denominator of the target ratio."),
          numberFactor("referenceHz", "Reference frequency", 220, 40, 880, 1, "Hz", "Reference used for the idealized beating calculation."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: ["marjieh-2024"],
      }),
      lesson("pitch-tuning", 3, {
        id: "timbre-changes-consonance",
        level: "critique",
        title: "Timbre Changes Consonance",
        shortTitle: "Timbre & consonance",
        question: "Why can the same fundamental interval change when its spectrum changes?",
        objective: "Compare partial coincidences and a transparent roughness proxy across timbres.",
        equation: "S(f) = sum a_k delta(f-k f0)",
        equationCaption: "The partial amplitudes define the synthetic spectrum used by the proxy.",
        predictionPrompt: "Predict how adding bright upper partials changes the displayed coincidence and roughness proxies.",
        experimentPrompt: "Hold the interval fixed while changing partial count or spectral roll-off.",
        interpretationPrompt: "Connect the model to empirical consonance research without universalizing preference.",
        transferPrompt: "Compare the same dyad with two instrumental registrations and describe, do not score, the change.",
        factors: [
          numberFactor("intervalCents", "Interval", 700, 0, 1200, 5, "cents", "Fundamental interval between the two synthetic tones."),
          numberFactor("partialCount", "Partials", 8, 1, 24, 1, "", "Number of harmonic partials in each tone."),
          numberFactor("rolloff", "Spectral roll-off", 1, 0.2, 3, 0.1, "power", "Amplitude exponent: a_k = 1/k^p."),
        ],
        claimIds: ["math.identity", ...contextualClaims],
        sourceIds: ["marjieh-2024"],
      }),
    ],
  },
  ...advancedLabDomains,
];

export const allLessons: readonly LabLesson[] = labCatalog.flatMap((domain) => domain.lessons);

export function domainById(id: string): LabDomain | undefined {
  return labCatalog.find((domain) => domain.id === id);
}

export function labLessonById(labId: string, lessonId: string): LabLesson | undefined {
  return domainById(labId)?.lessons.find((item) => item.id === lessonId);
}

export function lessonByRoute(hash: string): LabLesson | undefined {
  const match = /^#\/labs\/([^/]+)\/lessons\/([^/?#]+)$/.exec(hash);
  return match ? labLessonById(match[1], match[2]) : undefined;
}

export const defaultLabLesson = labCatalog[0].lessons[0];

if (!defaultLabLesson) {
  throw new Error("The curriculum must contain at least one lesson.");
}
