import {
  chordOptions,
  commonClaims,
  lesson,
  numberFactor,
  selectFactor,
  toggleFactor,
} from "./catalogSupport";
import type { LabDomain } from "./types";

export const advancedLabDomains: readonly LabDomain[] = [
  {
    id: "harmony-geometry",
    number: 5,
    title: "Harmony & Geometry",
    shortTitle: "Harmony",
    mark: "△",
    description: "Study pitch-class symmetries, interval structure, graphs, and voice-leading distance.",
    lessons: [
      lesson("harmony-geometry", 1, {
        id: "pitch-class-symmetry",
        level: "foundation",
        title: "Pitch-Class Symmetry",
        shortTitle: "Pitch-class symmetry",
        question: "Which interval properties survive transposition and inversion?",
        objective: "Apply T/I operations and compare interval-class vectors.",
        equation: "T_n(x)=x+n mod 12; I_n(x)=n-x mod 12",
        equationCaption: "The same index n is used directly in T_n and I_n on the twelve pitch classes.",
        predictionPrompt: "Predict whether the interval-class vector changes under the selected operation.",
        experimentPrompt: "Change transposition or inversion while holding the source set fixed.",
        interpretationPrompt: "State the mathematical invariant without claiming identical harmonic function.",
        transferPrompt: "Find one score transformation and name what the pitch-class model omits.",
        factors: [
          selectFactor("set", "Pitch-class set", "major", [
            { value: "major", label: "Major triad {0,4,7}" },
            { value: "minor", label: "Minor triad {0,3,7}" },
            { value: "quartal", label: "Quartal set {0,5,10}" },
            { value: "whole-tone", label: "Whole-tone {0,2,4,6}" },
          ], "Source pitch-class collection."),
          numberFactor("axis", "T/I index n", 0, 0, 11, 1, "pitch classes", "The n in T_n(x)=x+n and I_n(x)=n-x, both modulo 12."),
          toggleFactor("invert", "Use inversion", false, "Switch between transposition and inversion."),
        ],
        claimIds: commonClaims,
        sourceIds: ["frederick-2023"],
      }),
      lesson("harmony-geometry", 2, {
        id: "tonnetz-and-voice-leading",
        level: "model",
        title: "Tonnetz and Voice-Leading",
        shortTitle: "Voice-leading paths",
        question: "How can a graph and an assignment metric describe different kinds of harmonic proximity?",
        objective: "Calculate minimal circular semitone movement and compare it with a shortest path in a selected chord graph.",
        equation: "d_VL(A,B)=min_sigma sum_i |a_i-b_sigma(i)|_12; d_G(A,B)=min_P sum_(e in P) w(e)",
        equationCaption: "The assignment distance and graph-path cost are distinct, explicit proximity models.",
        predictionPrompt: "Predict which target chord is closer under the displayed metric.",
        experimentPrompt: "Change either the target chord or graph family, but not both, and compare the two proximity observables.",
        interpretationPrompt: "Explain why computed proximity does not prove tonal function or perceptual closeness.",
        transferPrompt: "Voice two chords on an instrument and compare embodied constraints with the abstract metric.",
        factors: [
          selectFactor("chordA", "Source chord", "C", chordOptions(), "Source triad."),
          selectFactor("chordB", "Target chord", "Am", chordOptions(), "Target triad."),
          selectFactor("metric", "Graph family", "tonnetz", [
            { value: "tonnetz", label: "P/L/R triadic graph" },
            { value: "chromatic", label: "Chromatic root-distance graph" },
          ], "P/L/R edges cost one transformation; chromatic edges are weighted by circular root distance in semitones."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: ["frederick-2023"],
      }),
      lesson("harmony-geometry", 3, {
        id: "chord-hypotheses",
        level: "critique",
        title: "Chord Hypotheses",
        shortTitle: "Chord hypotheses",
        question: "How should a chroma template's top three chord labels be checked?",
        objective: "Interpret ranked major, minor, and no-chord hypotheses rather than a single asserted label.",
        equation: "score(c)=cosine(chroma, template_c)",
        equationCaption: "Template similarity ranks hypotheses; it does not recover voicing, function, or complete score.",
        predictionPrompt: "Predict how spectral ambiguity changes the gap between the first and second hypotheses.",
        experimentPrompt: "Compare a clean synthetic chord with added ambiguity or local browser audio.",
        interpretationPrompt: "Use confidence separation and musical context to accept, revise, or reject the ranking.",
        transferPrompt: "Check the top three hypotheses against a notated or performed cadence.",
        factors: [
          numberFactor("root", "Synthetic root", 0, 0, 11, 1, "pitch class", "Root pitch class for the synthetic chroma fixture."),
          selectFactor("quality", "Synthetic quality", "major", [
            { value: "major", label: "Major" },
            { value: "minor", label: "Minor" },
          ], "Triad quality for the synthetic fixture."),
          numberFactor("ambiguity", "Spectral ambiguity", 0.15, 0, 1, 0.05, "", "Deterministic energy spread across unrelated pitch classes."),
        ],
        claimIds: ["measurement.local", "hypothesis.transcription", "heuristic.transparent", "recommendation.inquiry"],
        sourceIds: ["w3c-webaudio"],
        inputModes: ["synthetic", "microphone", "file"],
      }),
    ],
  },
  {
    id: "timbre-acoustics",
    number: 6,
    title: "Timbre & Acoustics",
    shortTitle: "Timbre",
    mark: "▥",
    description: "Connect resonance, partials, spectra, windows, sampling, aliasing, and envelopes.",
    lessons: [
      lesson("timbre-acoustics", 1, {
        id: "resonance-modes-partials",
        level: "foundation",
        title: "Resonance, Modes, and Partials",
        shortTitle: "Modes & partials",
        question: "How do boundary assumptions generate a family of resonant frequencies?",
        objective: "Calculate idealized string modes and construct an additive spectrum.",
        equation: "f_n = n v / (2L)",
        equationCaption: "Ideal fixed-string modes omit stiffness, damping, radiation, and instrument geometry.",
        predictionPrompt: "Predict how doubling length changes every idealized mode.",
        experimentPrompt: "Change length or mode count one at a time and inspect the partial series.",
        interpretationPrompt: "Separate an ideal mode calculation from a measured instrument spectrum.",
        transferPrompt: "Identify one real-instrument effect absent from the ideal string model.",
        factors: [
          numberFactor("length", "String length", 0.65, 0.2, 2, 0.01, "m", "Ideal vibrating length."),
          numberFactor("waveSpeed", "Wave speed", 143, 40, 500, 1, "m/s", "Ideal transverse wave speed."),
          numberFactor("partialCount", "Modes shown", 8, 1, 24, 1, "", "Number of ideal modes in the display."),
        ],
        claimIds: commonClaims,
        sourceIds: ["marjieh-2024"],
      }),
      lesson("timbre-acoustics", 2, {
        id: "fourier-windows-aliasing",
        level: "model",
        title: "Fourier, Windows, and Aliasing",
        shortTitle: "Fourier & aliasing",
        question: "What do frame size, windowing, and sample rate permit a spectrum to show?",
        objective: "Relate bin spacing to frame duration and fold frequencies above Nyquist.",
        equation: "Delta f = fs/N; f_alias = |((f+fs/2) mod fs)-fs/2|",
        equationCaption: "Finite sampled frames constrain frequency representation.",
        predictionPrompt: "Predict how doubling frame size changes frequency-bin spacing.",
        experimentPrompt: "Change frame size or sample rate separately and compare resolution and alias frequency.",
        interpretationPrompt: "Explain why a plotted peak is not infinitely precise or free of leakage.",
        transferPrompt: "Choose analysis settings for a low note and justify the time–frequency trade-off.",
        factors: [
          numberFactor("frequencyHz", "Signal frequency", 1000, 20, 30000, 10, "Hz", "Synthetic sinusoid before sampling."),
          selectFactor("sampleRateHz", "Sample rate", "48000", [
            { value: "22050", label: "22,050 Hz" },
            { value: "44100", label: "44,100 Hz" },
            { value: "48000", label: "48,000 Hz" },
          ], "Sampling frequency."),
          selectFactor("frameSize", "Hann frame", "2048", [
            { value: "2048", label: "2,048 samples" },
            { value: "4096", label: "4,096 samples" },
          ], "Analysis frame with 50% overlap in recorded-audio mode."),
        ],
        claimIds: commonClaims,
        sourceIds: ["w3c-webaudio"],
      }),
      lesson("timbre-acoustics", 3, {
        id: "time-varying-timbre",
        level: "critique",
        title: "Time-Varying Timbre",
        shortTitle: "Timbre through time",
        question: "Why can one spectrum not describe an evolving musical sound?",
        objective: "Relate envelope and modulation parameters to a time-indexed spectral-centroid proxy.",
        equation: "x(t)=A(t) sum a_k(t) sin(2 pi k f0 t)",
        equationCaption: "Both amplitude and partial weights may vary through time.",
        predictionPrompt: "Predict when the brightest point occurs under the selected envelope and modulation.",
        experimentPrompt: "Change attack or modulation depth while holding the other factors fixed.",
        interpretationPrompt: "Compare a trajectory with listening while retaining the uncalibrated boundary.",
        transferPrompt: "Describe the attack and decay of one instrumental tone with both words and a measured feature.",
        factors: [
          numberFactor("attackMs", "Attack", 80, 5, 1000, 5, "ms", "Duration of the synthetic rise."),
          numberFactor("decayMs", "Decay", 900, 100, 4000, 25, "ms", "Duration of the synthetic decay."),
          numberFactor("modulationHz", "Brightness modulation", 2, 0, 12, 0.25, "Hz", "Rate of deterministic partial-weight modulation."),
          numberFactor("modulationDepth", "Modulation depth", 0.45, 0, 1, 0.05, "", "Depth of spectral-centroid movement."),
        ],
        claimIds: ["model.deterministic", "measurement.local", "literature.context", "heuristic.transparent"],
        sourceIds: ["marjieh-2024", "w3c-webaudio"],
        inputModes: ["synthetic", "microphone", "file"],
      }),
    ],
  },
  {
    id: "probability-form",
    number: 7,
    title: "Probability & Form",
    shortTitle: "Probability",
    mark: "◇",
    description: "Use seeded chance, Markov memory, entropy, and surprisal without equating them with creativity.",
    lessons: [
      lesson("probability-form", 1, {
        id: "seeded-chance",
        level: "foundation",
        title: "Seeded Chance",
        shortTitle: "Seeded chance",
        question: "How can a stochastic rule produce an exactly reproducible classroom experiment?",
        objective: "Generate a seeded binary sequence and compare expected and observed proportions.",
        equation: "X_t ~ Bernoulli(p)",
        equationCaption: "A fixed pseudo-random seed reproduces one finite realization.",
        predictionPrompt: "Predict how closely the finite proportion will match p at the selected length.",
        experimentPrompt: "Change seed or length separately and compare finite-sample variation.",
        interpretationPrompt: "Distinguish a probability model, one realization, and a musical design decision.",
        transferPrompt: "Use one seeded rule to generate material you can revise rather than accept automatically.",
        factors: [
          numberFactor("probability", "Probability of A", 0.5, 0.05, 0.95, 0.05, "", "Bernoulli probability for event A."),
          numberFactor("length", "Sequence length", 16, 4, 128, 1, "events", "Number of generated events."),
          numberFactor("seed", "Seed", 2026, 0, 9999, 1, "", "Integer seed for reproducibility."),
        ],
        claimIds: commonClaims,
        sourceIds: [],
        seed: "factor:seed",
      }),
      lesson("probability-form", 2, {
        id: "markov-memory",
        level: "model",
        title: "Markov Memory",
        shortTitle: "Markov memory",
        question: "How does a transition rule create local dependence without planning a global form?",
        objective: "Generate a two-state Markov sequence and compare run length with the stationary distribution.",
        equation: "P(X_(t+1)=j | X_t=i) = P_ij",
        equationCaption: "The next-state distribution depends only on the current modeled state.",
        predictionPrompt: "Predict how a higher stay probability changes repeated runs.",
        experimentPrompt: "Change stay probability only; retain the seed for a controlled comparison.",
        interpretationPrompt: "Explain local memory without calling the chain a style model or composer.",
        transferPrompt: "Map states to musical actions and identify a formal behavior the first-order chain cannot create.",
        factors: [
          numberFactor("stayProbability", "Stay probability", 0.75, 0.05, 0.95, 0.05, "", "Probability of repeating the current state."),
          numberFactor("length", "Sequence length", 32, 4, 128, 1, "events", "Number of generated states."),
          numberFactor("seed", "Seed", 173, 0, 9999, 1, "", "Integer seed for reproducibility."),
        ],
        claimIds: commonClaims,
        sourceIds: [],
        seed: "factor:seed",
      }),
      lesson("probability-form", 3, {
        id: "entropy-surprisal-form",
        level: "critique",
        title: "Entropy, Surprisal, and Form",
        shortTitle: "Entropy & form",
        question: "What does information quantify, and what does it leave out about musical form?",
        objective: "Calculate entropy and event surprisal, then compare them with a finite seeded sequence.",
        equation: "H(X) = -sum p(x) log2 p(x)",
        equationCaption: "Entropy is expected information under a declared distribution, not creativity or quality.",
        predictionPrompt: "Predict where binary entropy is largest and how rare-event surprisal behaves.",
        experimentPrompt: "Change probability only, then inspect entropy, surprisal, and the generated sequence.",
        interpretationPrompt: "Name formal or contextual properties that the entropy value cannot encode.",
        transferPrompt: "Compare two musical sections with an explicit event alphabet and critique that representation.",
        factors: [
          numberFactor("probability", "Probability of A", 0.65, 0.05, 0.95, 0.05, "", "Declared probability for event A."),
          numberFactor("length", "Sample length", 24, 4, 128, 1, "events", "Finite generated sequence length."),
          numberFactor("seed", "Seed", 41, 0, 9999, 1, "", "Integer seed for the finite realization."),
        ],
        claimIds: [...commonClaims, "heuristic.transparent"],
        sourceIds: [],
        seed: "factor:seed",
      }),
    ],
  },
  {
    id: "measurement-inference",
    number: 8,
    title: "Measurement & Inference",
    shortTitle: "Measurement",
    mark: "⌁",
    description: "Track provenance, uncertainty, parameter recovery, and descriptive comparison.",
    lessons: [
      lesson("measurement-inference", 1, {
        id: "provenance-and-uncertainty",
        level: "foundation",
        title: "Provenance and Uncertainty",
        shortTitle: "Provenance",
        question: "What must accompany a number before it can function as evidence?",
        objective: "Connect sample count, deterministic noise, method, units, and an uncertainty interval.",
        equation: "CI_95 = mean +/- 1.96 s/sqrt(n)",
        equationCaption: "The displayed interval is a teaching approximation for a synthetic sample, not a universal guarantee.",
        predictionPrompt: "Predict how increasing sample count changes the interval width at fixed noise.",
        experimentPrompt: "Change sample count only and compare uncertainty with the same synthetic seed.",
        interpretationPrompt: "State the population, method, assumptions, and calibration status needed for the claim.",
        transferPrompt: "Rewrite one unsupported musical number as a bounded, provenance-rich observation.",
        factors: [
          numberFactor("sampleCount", "Sample count", 24, 4, 256, 1, "", "Number of deterministic synthetic observations."),
          numberFactor("trueValue", "Generating value", 100, 0, 200, 1, "units", "Known center of the synthetic fixture."),
          numberFactor("noise", "Noise scale", 8, 0, 40, 0.5, "units", "Deterministic pseudo-random variation scale."),
          numberFactor("seed", "Seed", 9, 0, 9999, 1, "", "Seed recorded with the synthetic sample."),
        ],
        claimIds: ["model.deterministic", "measurement.local", "heuristic.transparent", "recommendation.inquiry"],
        sourceIds: ["w3c-webaudio", "w3c-mediacapture"],
        seed: "factor:seed",
      }),
      lesson("measurement-inference", 2, {
        id: "recovering-parameters",
        level: "model",
        title: "Recovering Parameters",
        shortTitle: "Parameter recovery",
        question: "Can the analysis recover a known generating tempo from noisy synthetic onsets?",
        objective: "Estimate tempo from bounded inter-onset intervals and inspect bias and spread.",
        equation: "b_hat = 60 / median(Delta t)",
        equationCaption: "Median-interval recovery is transparent but fails under subdivisions, missing events, and tempo change.",
        predictionPrompt: "Predict how onset jitter changes recovered tempo and interval spread.",
        experimentPrompt: "Change jitter or sample count separately while the generating tempo stays known.",
        interpretationPrompt: "Use recovery error to critique the method, not to grade a performance.",
        transferPrompt: "Design one synthetic failure case before applying an estimator to recorded sound.",
        factors: [
          numberFactor("tempoBpm", "Generating tempo", 120, 40, 220, 1, "BPM", "Known tempo used to generate synthetic onsets."),
          numberFactor("jitterMs", "Onset variation", 18, 0, 120, 1, "ms", "Deterministic onset displacement scale."),
          numberFactor("sampleCount", "Onsets", 24, 6, 128, 1, "", "Number of synthetic onsets."),
          numberFactor("seed", "Seed", 77, 0, 9999, 1, "", "Seed recorded with the fixture."),
        ],
        claimIds: ["model.deterministic", "hypothesis.transcription", "heuristic.transparent"],
        sourceIds: ["snyder-2024"],
        seed: "factor:seed",
      }),
      lesson("measurement-inference", 3, {
        id: "compare-without-grading",
        level: "critique",
        title: "Compare Without Grading",
        shortTitle: "Descriptive comparison",
        question: "How can two event sets be compared without turning difference into a score?",
        objective: "Summarize signed alignment with median and IQR while retaining direction and provenance.",
        equation: "d_i = observed_i - reference_i",
        equationCaption: "Median and IQR describe the selected event alignment; no target grade is defined.",
        predictionPrompt: "Predict how a systematic offset differs from increased spread in the summary.",
        experimentPrompt: "Change center or spread separately and compare descriptive alignment statistics.",
        interpretationPrompt: "Describe timing relation without using better, worse, accurate, or inaccurate.",
        transferPrompt: "Write a neutral rehearsal observation that keeps direction, variability, and context.",
        factors: [
          numberFactor("offsetMs", "Systematic offset", 22, -150, 150, 1, "ms", "Center of the synthetic event differences."),
          numberFactor("spreadMs", "Difference spread", 18, 0, 100, 1, "ms", "Deterministic variability around the center."),
          numberFactor("eventCount", "Event pairs", 16, 4, 64, 1, "", "Number of paired synthetic events."),
          numberFactor("seed", "Seed", 33, 0, 9999, 1, "", "Seed recorded with the comparison."),
        ],
        claimIds: ["model.deterministic", "measurement.local", "recommendation.inquiry"],
        sourceIds: ["demos-palmer-2023", "abalde-2024"],
        seed: "factor:seed",
      }),
    ],
  },
];
